#!/bin/bash

ssh root@$1 "cd ~/ && git clone https://github.com/endermAH/Netcrecker-project.git"

GIT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2)

ssh root@$1  "cd ~/Netcrecker-project && git pull"
ssh root@$1  "cd ~/Netcrecker-project && git checkout $GIT_BRANCH"

ssh root@$1 "/root/Netcrecker-project/roles/ansible_install/ansible_install.sh"

ssh root@$1  "cd ~/Netcrecker-project && ansible-playbook -i inventory.ini jenkins-vps-playbook.yml"
#ssh root@$1  "cd ~/Netcrecker-project && ansible-playbook -i inventory.ini psql-vps-playbook.yml"
#ssh root@$1  "cd ~/Netcrecker-project && ansible-playbook -i inventory.ini liferay-vps-playbook.yml"
