#!/bin/bash

NORMAL='\033[0m'
GREEN='\033[0;32m'
MAGENTA='\033[0;35m'

DO_FING=$(ssh-keygen -E md5 -lf ~/.ssh/id_rsa.pub | awk '{print $2}' | cut -c 5-)
DO_TOKEN="98fcb6662e0ecdef1501f564390a5f42b9cbefe7689ca99a0d091b3b117c72c6"

echo -e [${MAGENTA}TERRAFORM:${NORMAL} DESTROYING INFRASTRUCTURE] =======================
echo You can see progress in ./logs/terraform_destroy.log

cd ./terraform && terraform destroy -auto-approve \
  -var "do_token=${DO_TOKEN}" \
  -var "pub_key=${HOME}/.ssh/id_rsa.pub" \
  -var "pvt_key=${HOME}/.ssh/id_rsa" \
  -var "ssh_fingerprint=${DO_FING}" &>> ../logs/terraform_destroy.log

echo ""
echo -e [${MAGENTA}TERRAFORM:${NORMAL} CREATING DROPLETS] =================================
echo You can see progress in ./logs/terraform_apply.log

terraform apply -auto-approve \
  -var "do_token=${DO_TOKEN}" \
  -var "pub_key=${HOME}/.ssh/id_rsa.pub" \
  -var "pvt_key=${HOME}/.ssh/id_rsa" \
  -var "ssh_fingerprint=${DO_FING}" &>> ../logs/terraform_apply.log

echo -e [${MAGENTA}TERRAFORM:${NORMAL} FINISHED WITH EXIT CODE $?] =======================
echo ""
echo -e [${MAGENTA}SHELL:${NORMAL} KEY EXCHANGING] ========================================

jenkins_ip="178.128.139.237"
psql_ip="134.209.137.88"
liferay_ip="178.128.142.117"

echo ""
echo -e ${GREEN}[$jenkins_ip]${NORMAL} Jenkins ip
echo -e ${GREEN}[$psql_ip]${NORMAL} Postgresql ip
echo -e ${GREEN}[$liferay_ip]${NORMAL} Liferay ip
echo ""

rm ~/.ssh/known_hosts
echo Connecting to root@$jenkins_ip - ssh-keygen

ssh root@$jenkins_ip "echo '    StrictHostKeyChecking no' >> /etc/ssh/ssh_config"
ssh root@$jenkins_ip "ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ''"
scp root@$jenkins_ip:~/.ssh/id_rsa.pub ./key
ssh root@$jenkins_ip "mkdir -p /opt/tomcat/.ssh && cp ~/.ssh/id_rsa.pub /opt/tomcat/.ssh/id_rsa.pub && cp ~/.ssh/id_rsa /opt/tomcat/.ssh/id_rsa"
ssh root@$jenkins_ip "cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"
KEY=$(cat ./key)
ssh root@$psql_ip "echo $KEY >> ~/.ssh/authorized_keys"
ssh root@$liferay_ip "echo $KEY >> ~/.ssh/authorized_keys"
rm ./key

echo ""
echo -e [${MAGENTA}SHELL:${NORMAL} INSTALL DEPENDENCIES] ================================
cd ..
echo [*] Installing Jenkins dependencies
ssh root@$jenkins_ip "apt-get update -y && apt-get install -y ansible python python3 python-pip python-yaml python-jinja2 python-httplib2 git" &>> ./logs/dependencies.log
echo [*] Installing PostgreSQL dependencies
ssh root@$psql_ip "apt-get update -y && apt-get install -y python python3 python-pip python-yaml python-jinja2 python-httplib2 git" &>> ./logs/dependencies.log
echo [*] Installing Liferay dependencies
ssh root@$liferay_ip "apt-get update -y && apt-get install -y python python3 python-pip python-yaml python-jinja2 python-httplib2 python-paramiko python-pkg-resources git unzip" &>> ./logs/dependencies.log
echo ""
echo You can check installation log in ./logs/dependencies.log
echo ""
echo -e [${MAGENTA}SHELL:${NORMAL} DEPLOY JENKINS] ======================================
ssh root@$jenkins_ip "git clone https://github.com/endermAH/Netcrecker-project.git"

#scp ~/liferay_files.zip root@$jenkins_ip:~/
#ssh root@$jenkins_ip "unzip ~/liferay_files.zip -d ~/"

ssh root@$jenkins_ip "ansible-playbook -i ~/Netcrecker-project/inventory.ini ~/Netcrecker-project/jenkins-vps-playbook.yml"

echo ""
echo -e [${MAGENTA}JENKINS:${NORMAL} DEPLOY POSTGRESQL AND LIFERAY] =====================
echo -e Go to ${GRENN}${jenkins_ip}:8080${NORMAL} and check deployment progress!
