#!/bin/bash

#./ter_log.sh apply

jenkins_ip=$(./parse_ip.py jenkins)
psql_ip=$(./parse_ip.py psql)
liferay_ip="178.128.142.117"

rm ~/.ssh/known_hosts

scp root@$jenkins_ip:~/.ssh/id_rsa.pub ./key
KEY=$(cat ./key)
ssh root@$psql_ip "echo $KEY >> ~/.ssh/authorized_keys"
ssh root@$liferay_ip "echo $KEY >> ~/.ssh/authorized_keys"
rm ./key
