#!/bin/bash

#./ter_log.sh apply

jenkins_ip=$(./parse_ip.py jenkins)
echo Jenkins ip - $jenkins_ip
psql_ip=$(./parse_ip.py psql)
echo Postgresql ip - $psql_ip
liferay_ip="178.128.142.117"

rm ~/.ssh/known_hosts

echo Connecting to root@$jenkins_ip - ssh-keygen
ssh root@$jenkins_ip "ssh-keygen"
scp root@$jenkins_ip:~/.ssh/id_rsa.pub ./key
KEY=$(cat ./key)
ssh root@$psql_ip "echo $KEY >> ~/.ssh/authorized_keys"
ssh root@$liferay_ip "echo $KEY >> ~/.ssh/authorized_keys"
rm ./key
